upstream fastapi_backend {
    server backend:8000;

    keepalive 32;
}

upstream nextjs_frontend {
    server frontend:3000;
    keepalive 32;
}

# http://api.domain.uz -> https://api.domain.uz
# http://domain.uz -> https://api.domain.uz
server {
    # 80 порт для HTTP
    # 443 порт для HTTPS
    listen 80;

    server_name api.testsage.uz www.api.testsage.uz www.testsage.uz testsage.uz;
    # host = domain.uz
    #http://domain.uz/todos
    # request_uri = /todos
    # http://localhost/

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout 60s;
    }

}

# https://api.domain.uz
server {
    listen 443 ssl;

    server_name api.testsage.uz www.api.testsage.uz;

    # Публичный Сертификат
    ssl_certificate /etc/letsencrypt/live/testsage.uz/fullchain.pem;
    # Приватный Сертификат
    ssl_certificate_key /etc/letsencrypt/live/testsage.uz/privkey.pem;

    # TLS 1.0 1.1 1.2 1.3
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass http://fastapi_backend;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# domain.uz
server {
    listen 443 ssl;

    server_name testsage.uz www.testsage.uz;

    # Публичный Сертификат
    ssl_certificate /etc/letsencrypt/live/testsage.uz/fullchain.pem;
    # Приватный Сертификат
    ssl_certificate_key /etc/letsencrypt/live/testsage.uz/privkey.pem;

    # TLS 1.0 1.1 1.2 1.3
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass http://nextjs_frontend;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
